-- Supabase SQL for a simple order record table.
-- Run this in Supabase SQL Editor or as part of your migration process.

create table if not exists orders (
  id bigint generated by default as identity primary key,
  user_id uuid not null,
  items jsonb not null,
  total numeric(10,2) not null,
  status text not null default 'pending',
  created_at timestamptz not null default now()
);
